/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './App/routes/__root'
import { Route as IndexRouteImport } from './App/routes/index'
import { Route as BooksIndexRouteImport } from './App/routes/books/index'
import { Route as ProfilesUserNameRouteImport } from './App/routes/profiles/$userName'
import { Route as BooksTitleRouteImport } from './App/routes/books/$title'
import { Route as AuthRegisterRouteImport } from './App/routes/auth/register'
import { Route as AuthLoginRouteImport } from './App/routes/auth/login'
import { Route as AccountUsernameRouteImport } from './App/routes/account/$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesUserNameRoute = ProfilesUserNameRouteImport.update({
  id: '/profiles/$userName',
  path: '/profiles/$userName',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksTitleRoute = BooksTitleRouteImport.update({
  id: '/books/$title',
  path: '/books/$title',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountUsernameRoute = AccountUsernameRouteImport.update({
  id: '/account/$username',
  path: '/account/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/$username': typeof AccountUsernameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$title': typeof BooksTitleRoute
  '/profiles/$userName': typeof ProfilesUserNameRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/$username': typeof AccountUsernameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$title': typeof BooksTitleRoute
  '/profiles/$userName': typeof ProfilesUserNameRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/$username': typeof AccountUsernameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/books/$title': typeof BooksTitleRoute
  '/profiles/$userName': typeof ProfilesUserNameRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/$username'
    | '/auth/login'
    | '/auth/register'
    | '/books/$title'
    | '/profiles/$userName'
    | '/books'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/$username'
    | '/auth/login'
    | '/auth/register'
    | '/books/$title'
    | '/profiles/$userName'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/account/$username'
    | '/auth/login'
    | '/auth/register'
    | '/books/$title'
    | '/profiles/$userName'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountUsernameRoute: typeof AccountUsernameRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  BooksTitleRoute: typeof BooksTitleRoute
  ProfilesUserNameRoute: typeof ProfilesUserNameRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$userName': {
      id: '/profiles/$userName'
      path: '/profiles/$userName'
      fullPath: '/profiles/$userName'
      preLoaderRoute: typeof ProfilesUserNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$title': {
      id: '/books/$title'
      path: '/books/$title'
      fullPath: '/books/$title'
      preLoaderRoute: typeof BooksTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$username': {
      id: '/account/$username'
      path: '/account/$username'
      fullPath: '/account/$username'
      preLoaderRoute: typeof AccountUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountUsernameRoute: AccountUsernameRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  BooksTitleRoute: BooksTitleRoute,
  ProfilesUserNameRoute: ProfilesUserNameRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
